let myDate = new Date()
// console.log(myDate.toDateString())
// console.log(myDate.toString())
// console.log(myDate.toISOString())
// console.log(myDate.toJSON())
// console.log(myDate.toLocaleDateString())
// console.log(myDate.toLocaleString())
let newDate = new Date()
console.log(newDate);
console.log(newDate.getDate() + 1)
console.log(newDate.getDay())
